[tool.poetry]
name = "repl_nix_Discord-AI-Chatbot-2"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.10"
Flask = "^2.3.2"
langdetect = "^1.0.9"
python-dotenv = "^1.0.0"
youtube-transcript-api = "^0.6.0"
aiohttp = "^3.8.4"
discord = "^2.2.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
